spring:
  main:

    log-startup-info: true
    banner-mode: off

    jpa:
      properties:
        hibernate:
          enable_lazy_load: true
    jvm-args:
      -Djava.instrument.traceUsage
      -XX:+EnableDynamicAgentLoading

logging:
  level:
    org.zalando.logbook: TRACE